version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_USER: richi
        NODE_VERSION: 21-bookworm
    user: "1000:1000"
    environment:
      - UID: 1000
      - GID: 1000
    volumes:
      - ./:/usr/src/app
    command: tail -f /dev/null
    ports:
      - "8080:8080"
      - "3000:3000"
      - "1022:22"
